apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argotest
  namespace: argocd
spec:
  destination:
    namespace: argotest
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/akinolafusi/argotest.git
    path: ./guestbook.yaml
    targetRevision: HEAD
